const CardData = [
  {
    name: "AHUS",
    mapImage: "./img/ahus.png",
    image: "./img/1.jpg",
    date: "01.01.2022",
    distance: 9,
    link: "https://www.strava.com/activities/6456288414",
    weather: "-4°C ❄️",
  },
  {
    name: "AHUS",
    mapImage: "./img/ahus.png",
    image: "./img/ahus.png",
    date: "01.01.2022",
    distance: 9,
    link: "https://www.strava.com/activities/6456288414",
    weather: "-4°C ❄️",
  },
  {
    name: "AHUS",
    mapImage: "./img/ahus.png",
    image: "./img/1.jpg",
    date: "01.01.2022",
    distance: 9,
    link: "https://www.strava.com/activities/6456288414",
    weather: "-4°C ❄️",
  },
  {
    name: "AHUS",
    mapImage: "./img/ahus.png",
    image: "./img/1.jpg",
    date: "01.01.2022",
    distance: 9,
    link: "https://www.strava.com/activities/6456288414",
    weather: "-4°C ❄️",
  },
  {
    name: "AHUS",
    mapImage: "./img/ahus.png",
    image: "./img/ahus.png",
    date: "01.01.2022",
    distance: 9,
    link: "https://www.strava.com/activities/6456288414",
    weather: "-4°C ❄️",
  },
  {
    name: "AHUS",
    mapImage: "./img/ahus.png",
    image: "./img/1.jpg",
    date: "01.01.2022",
    distance: 9,
    link: "https://www.strava.com/activities/6456288414",
    weather: "-4°C ❄️",
  },
];

export default CardData;
